require 'open-uri'
require 'json'
require 'mongo_mapper'
require 'nokogiri'
require 'mechanize'
require 'csv'
require 'uri'

require_relative 'council_data/db'
require_relative 'council_data/councils'
require_relative 'council_data/council_data'